# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo hello > world.txt
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: world.txt
    - uses: actions/download-artifact@v2
      with:
        name: my-artifact
    - name: Display structure of downloaded files
      run: ls -R
