# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      run: echo "testing" > math-homework.txt
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v1
      with:
        name: testing
        path: math-homework.txt
